[package]
name = "generator"
version = "0.1.0"
edition = "2018"

[dependencies]
minifb = "0.19.3"
image = "0.23.14"
auto_ops = "0.3.0"
itertools = "0.10.1"

[lib]
name = "generator"

[[bin]]
name = "generate"
path = "scripts/generate.rs"
